apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: client
spec:
  template:
    metadata:
      name: ${REVISION_NAME}
    spec:
      containers:
      - image: ${IMAGE}
        ports:
          containerPort: 3000
