# Generated by Django 5.0.6 on 2024-06-09 02:11

from django.db import migrations
from django.utils import timezone


def create_first_generation(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Generation = apps.get_model("api", "Generation")
    Generation.objects.create(active_date=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_first_generation),
    ]
