# Generated by Django 5.0.6 on 2024-09-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_art_artist_remove_art_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newvote',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='newvote',
            name='user',
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dna', models.TextField()),
                ('public_link', models.URLField()),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.votinguser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NewArtist',
        ),
        migrations.DeleteModel(
            name='NewVote',
        ),
    ]
