version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env.test

  tests:
    build: .
    command: python manage.py test
    volumes:
      - ./:/home/appuser/
    ports:
      - 8000:8000
    env_file:
      - ./.env.test
    depends_on:
      - db

volumes:
  postgres_data:
