version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #ports:
    #  - 5431:5432
    env_file:
      - ./.env

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/appuser/
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}
      # x11 forwarding, to connect to the host x11 port.
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:
