services:
  tests:
    build: .
    entrypoint: python manage.py test
    volumes:
      - ./:/home/appuser/
      # x11 forwarding, to connect to the host x11 port.
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file:
      - ./.env.test
    network_mode: host
