version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env.test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tests:
    build: .
    entrypoint: python manage.py test
    volumes:
      - ./:/home/appuser/
    env_file:
      - ./.env.test
    depends_on:
      - db

volumes:
  postgres_data:
