version: '3.9'

services:
  db-test:
    image: postgres:15
    restart: always
    env_file:
      - ./.env.test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tests:
    build: .
    entrypoint: python manage.py test
    volumes:
      - ./:/home/appuser/
      # x11 forwarding, to connect to the host x11 port.
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file:
      - ./.env.test
    depends_on:
      - db-test

volumes:
  postgres_data:
