name: CI API

on:
  push:
    paths:
      - api/**
      - .github/workflows/ci.api.yaml

defaults:
  run:
    working-directory: api

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run Tests
        run: make test
