name: CI Infra

on:
  push:
    paths:
      - infra/**
      - .github/workflows/ci.infra.yaml

defaults:
  run:
    working-directory: infra/

jobs:
  check-terraform-format:
    name: Check Terraform format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4
          terraform_wrapper: false
      - name: Run infra-lint
        run: |
          echo "If this fails, run 'make infra-format'"
          make infra-lint
