name: CI Painter API

on:
  push:
    paths:
      - painter_api/**
      - .github/workflows/ci.painter_api.yaml

defaults:
  run:
    working-directory: painter_api

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DISPLAY: :99.0

    steps:
      - uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"


      - run: sudo apt-get install xvfb
      - run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run Tests
        run: make test
