name: Terraform CD

on:
  push:

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_CD }}
  PROJECT: "artist-2d"

jobs:
  tf_bootstrap:
    name: "Terraform Bootstrap"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: infra/bootstrap

    env:
      STAGE: "bootstrap"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4

      - run: ../setbucket.sh
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan -no-color

      - run: terraform apply -no-color -auto-approve
        if: github.ref_name == 'main'

  tf_app:
    name: "Terraform App"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: infra/app

    env:
      STAGE: "app"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4

      - run: cd .. && ./setbucket.sh
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan -no-color

      - run: terraform apply -no-color -auto-approve
        if: github.ref_name == 'main'
