name: Test CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: :99.0

    steps:
    - uses: actions/checkout@v2

    - name: Install OS packages
      run: sudo apt-get install software-properties-common
      run: sudo add-apt-repository ppa:deadsnakes/ppa
      run: sudo apt-get update
      run: sudo apt-get install python3.8 python3-tk
      run: sudo apt-get install xvfb
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Setup application
      run: make setup

    - name: Run tests
      run: make test
