name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OS packages
      run: sudo apt-get install python3-tk

    - name: Setup application
      run: make setup

    - name: Run tests
      run: make test
